#!/usr/bin/env node
/**
 * Splice `src/client/parts/*.js` into `src/client/template.js` and write
 * `client.js` — the classic script DSH actually serves.
 *
 * Zero dependencies on purpose (same rule as the rest of this repository): the
 * operation is one string replacement, and a bundler would add a build graph to a
 * package whose whole point is to be a single Loader row.
 *
 *   node tools/build-client.mjs           write client.js
 *   node tools/build-client.mjs --check   exit 1 when client.js is stale
 *
 * The parts share one factory scope and are concatenated in filename order, so the
 * numeric prefixes ARE the dependency order for anything evaluated at module
 * materialisation. `client.js` is committed; `--check` is what keeps it honest.
 * @module dsh-anagenesis-window/tools/build-client
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = resolve(here, '..')
const renderDir = join(root, 'src', 'render')
const partsDir = join(root, 'src', 'client', 'parts')
const templatePath = join(root, 'src', 'client', 'template.js')
const outputPath = join(root, 'client.js')

const BANNER = `/* eslint-disable */
/**
 * dsh-anagenesis-window — client half (BUILT ARTIFACT — do not edit).
 *
 * Generated by tools/build-client.mjs from src/client/template.js,
 * src/render/*.js (the shared pure render layer) and src/client/parts/*.js.
 * Edit those, then run \`npm run build:client\`; \`npm run check\` fails when
 * this file is stale.
 *
 * The render layer is spliced in FIRST and verbatim: it is the same source
 * Node-side previews and screenshots evaluate through tools/render-lib.mjs,
 * so "what I screenshotted" and "what the window draws" cannot drift.
 *
 * Contract of this file, fixed by @deepseek-ai/dsh-client-modules:
 *   - classic script, first statement \`window.__ModuleLoader__.load({...})\`;
 *   - \`id\` equals the package name;
 *   - no top-level import/export; \`require\` is the closed platform table.
 */

`

const renderParts = readdirSync(renderDir)
  .filter((name) => name.endsWith('.js'))
  .sort()
const parts = readdirSync(partsDir)
  .filter((name) => name.endsWith('.js'))
  .sort()

if (renderParts.length === 0) {
  console.error(`build-client: no render parts in ${renderDir}`)
  process.exit(1)
}
if (parts.length === 0) {
  console.error(`build-client: no client parts in ${partsDir}`)
  process.exit(1)
}

const template = readFileSync(templatePath, 'utf8')
const markers = template.split('__PARTS__').length - 1
if (markers !== 1) {
  console.error(`build-client: template must contain exactly one __PARTS__ marker, found ${markers}`)
  process.exit(1)
}

const splice = (dir, names) => names
  .map((name) => `    /* ── part: ${name} ${'─'.repeat(Math.max(1, 60 - name.length))} */\n`
    + readFileSync(join(dir, name), 'utf8').replace(/\s*$/, '\n'))
  .join('\n')

const body = splice(renderDir, renderParts) + '\n' + splice(partsDir, parts)

const output = BANNER + template.replace('__PARTS__', body.replace(/\s*$/, ''))

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(outputPath, 'utf8')
  } catch {
    console.error(`build-client: ${outputPath} is missing — run \`npm run build:client\``)
    process.exit(1)
  }
  if (current !== output) {
    console.error('build-client: client.js is STALE with respect to src/render/* or src/client/parts/* — run `npm run build:client`')
    process.exit(1)
  }
  console.log(`build-client: client.js is up to date (${renderParts.length} render + ${parts.length} client parts, ${output.length} bytes)`)
  process.exit(0)
}

writeFileSync(outputPath, output, 'utf8')
console.log(`build-client: wrote client.js (${renderParts.length} render + ${parts.length} client parts, ${output.length} bytes)`)
for (const name of renderParts) console.log(`  · render/${name}`)
for (const name of parts) console.log(`  · client/${name}`)